### ISSUE TITLE
Problems after 3.1.0 with ACD-1000 and AWMR-230

### ISSUE THREAD

**Issue by dENNtoet** [athombv/nl.klikaanklikuit#18]
After the 3.1.0 update I have serious problems with my ACD-1000 and AWMR-230 devices. 

The ACD-1000 does **not always** receive the signal (1m or 2m next to Homey). It used to work flawless, I did not change anything to the setup. 

The AWMR-230 is **even worse** than the ACD-1000 it's a miracle if the signal comes across.

I rebooted the microcontroller atleast 4 times, rebooted Homey 2 times. Still nothing.

There are more people with problems: https://forum.athom.com/discussion/1109/kaku-coco/p7

**Comment by Povlov** [comment]
After the update Kaku 3.1.0 17 hours ago, all my Kaku actions were numb. A restart of the app, no result. Restart of the microcontroller (settings for geeks), no result. Restart of the Homey, no result.

**Comment by Veldkornet** [comment]
I'm having the same problem with my ACD-1000 after 3.1.0, will do some more testing to see if any of my other devices are affected.

**Comment by Barbados02** [comment]
I have the same issue with my homey.
Before the KIKA app update i had no problem.
Homey running 1.2.2

**Comment by OpenMindNL** [comment]
Similar problems over here... several ACD-1000s and two ACD-3500s sometimes work and sometimes they don't

**Comment by Povlov** [comment]
Nice to have things working again! Tx Athom!

**Comment by bvdbos** [comment]
fixed in 3.1.1 for me

**Comment by harryba** [comment]
Still having problems with the ACD-1000, Homey doenst send any signals to it.
It receives signals if i use a kaku remote and changes state according to the button used.
So it seems Homey receives signals, but isnt sending them.
It never worked for me on this Homey, since i have it for 4 days now.

**Comment by dENNtoet** [comment]
Fixed with the rollback to update 3.1.1

**Comment by fvanbeenen** [comment]
Fixed with the rollback to update 3.1.1? How do you do this?
